### ISSUE TITLE
robot model prefix support

### ISSUE THREAD

**Issue by athackst** [osrf/rvizweb#7]
We use the "prefix" option in robot_state_publisher to disambiguate multiples.  The QT RViz has a "TF Prefix"  parameter that is used to read in a prefixed TF tree.   Would it be possible to add that here?

**Comment by athackst** [comment]
I think you misunderstood.

It's the robot model plugin that needs the TF prefix, not the TF component.  The URDF is not prefixed, but our TFs have a published prefix from robot_state_publisher

<img width="1176" alt="screen shot 2018-12-17 at 5 49 35 pm" src="https://user-images.githubusercontent.com/6098197/50127034-330bcb80-0224-11e9-9f4e-e0d03149d29e.png">

**Comment by jubeira** [comment]
Sorry for the misunderstanding; now I see it! I'll send a PR soon with the patch.

**Comment by chapulina** [comment]
Is this _the_ TF prefix that has been [deprecated since Hydro](http://wiki.ros.org/hydro/Migration#tf2.2BAC8-Migration.Removal_of_support_for_tf_prefix)? It was my understanding that its use has been discouraged for many years now.

**Comment by athackst** [comment]
No, this is the tf_prefix associated with the robot_state_publisher http://wiki.ros.org/robot_state_publisher  and therefore has a supporting tf_prefix in the robot_model display in rviz.

**Comment by chapulina** [comment]
If it's really something else, the terms are very confusing. On the `robot_state_publisher` link there's a link to `tf_prefixes` which leads to this TF page: http://wiki.ros.org/tf/Theory. The page doesn't mention deprecations, but it could just be very outdated.

In any case, I was mainly curious, since we've removed all support for `tf_prefix` from `gazebo_ros_pkgs` when porting to ROS2. If RViz currently supports `tf_prefix`, I think it makes sense for RvizWeb to support it as well, for completeness.
